version: '3'

volumes:
  db_data:
    external: false

networks:
  app_network:
    external: false

services:
  # frontend:
  #   image: node:alpine
  #   working_dir: /frontend
  #   command: sh -c 'npm ci && npm start'
  #   volumes:
  #     - ./frontend:/frontend
  #   environment:
  #     - PORT: 3000
  #     - API_URL: http://localhost:3005
  #   ports:
  #     - 3000:3000

  backend:
    image: node:alpine
    working_dir: /backend
    command: sh -c 'npm ci && npm run dev'
    volumes:
      - ./backend:/backend
    environment:
      - PORT=3005
      - DB_HOST=db
    ports:
      - 3005:3005
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    # ports:
    #   - 3005:3005
