version: '3'

volumes:
  db_data:
    external: false
  backend_modules:
    external: false
  frontend_modules:
    external: false

networks:
  app_network:
    external: false

services:
  # frontend:
  #   image: node
  #   working_dir: /frontend
  #   command: sh -c 'npm install && npm start'
  #   volumes:
  #     - ./frontend:/frontend
  #     - frontend_modules:/frontend/node_modules
  #   environment:
  #     - PORT: 3000
  #     - API_URL: http://localhost:3005
  #   ports:
  #     - 3000:3000

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - app_network
    depends_on:
      - backend
      # - frontend

  backend:
    image: node
    working_dir: /backend
    command: sh -c 'npm install && npm run migrate && npx concurrently "npm run seed:watch" "npm run start:watch" "npm run test -- --watchAll"'
    volumes:
      - ./backend:/backend
      - backend_modules:/backend/node_modules
    environment:
      - PORT=80
      - DB_HOST=db
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
    # ports:
    #   - 5432:5432
